# GitHub Actions

name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stellar/stellar-cli@v22
        continue-on-error: true
      - name: Install wasm target
        run: rustup target add wasm32v1-none
      - name: Build WASM
        run: cargo build --release --target wasm32v1-none --workspace --locked
